export const ovpn = {
    apiUrl: 'https://windscribe.com/getconfig/openvpn',
    extension: 'ovpn',
    port: '54783',
    protocol: 'UDP',
    version: '3b',
};

export const wireguard = {
    apiUrl: 'https://windscribe.com/getconfig/wireguard',
    extension: 'conf',
    port: '65142',
    pubKey: ''
}

export const outputDir = 'output';
export const workerCount = 4;
export const sessionAuthHash = '';
export const locations = [
    '354:Adelaide - Lofty',
    '319:Adelaide - Oval',
    '229:Amsterdam - Bicycle',
    '289:Amsterdam - Red Light',
    '120:Amsterdam - Stroopwafel',
    '193:Amsterdam - Tulip',
    '218:Ashdod - Yam Park',
    '247:Athens - Odeon',
    '109:Atlanta - Mountain',
    '331:Atlanta - Piedmont',
    '352:Auckland - Hauraki',
    '251:Auckland - Parnell',
    '361:Bangkok - Chatuchak',
    '415:Bangkok - Lumphini',
    '239:Barcelona - Batllo',
    '288:Belgrade - Rakia',
    '302:Bend - Oregon Trail',
    '360:Bogota - Rololandia',
    '408:Boston - Harvard',
    '298:Boston - MIT',
    '213:Bratislava - Devin Castle',
    '225:Brisbane - Bad Koala',
    '357:Brisbane - Good Koala',
    '431:Brussels - Funfrites',
    '99:Brussels - Guildhouse',
    '105:Bucharest - No Vampires',
    '430:Bucharest - Noctropolis',
    '90:Budapest - Danube',
    '438:Budapest - Goulash',
    '278:Buenos Aires - Tango',
    '281:Buffalo - Bill',
    '439:Calgary - Chinook',
    '303:Charlotte - Earnhardt',
    '63:Chicago - Cub',
    '323:Chicago - Wrigley',
    '210:Chisinau - Dendrarium',
    '146:Cleveland - Brown',
    '429:Copenhagen - Hyggenhagen',
    '153:Copenhagen - LEGO',
    '192:Dallas - BBQ',
    '86:Dallas - Ranch',
    '414:Dallas - Trinity',
    '145:Denver - Barley',
    '368:Detroit - Coney Dog',
    '304:Dubai - Khalifa',
    '370:Dublin - Dullahan',
    '400:Dublin - Grafton',
    '369:Edinburgh - Keeper Willie',
    '113:Frankfurt - Castle',
    '228:Frankfurt - Wurstchen',
    '85:Gdansk - Motlawa',
    '386:Halifax - Crosby',
    '122:Hanoi - Red River',
    '98:Helsinki - Sauna',
    '186:Helsinki - Tram',
    '189:Hong Kong - Phooey',
    '26:Hong Kong - Victoria',
    '424:Houston - Space City',
    '405:Istanbul - Lygos',
    '416:Jakarta - Ancol',
    '164:Johannesburg - District',
    '232:Johannesburg - Lindfield',
    '409:Johannesburg - Springbok',
    '371:Kansas City - Glinda',
    '270:Kuala Lumpur - Perdana',
    '383:Kyiv - Ghost',
    '435:Lagos - Lekki',
    '183:Las Vegas - Casino',
    '367:Lima - Amaru',
    '432:Limassol - Amathusia',
    '249:Lisbon - Bairro',
    '441:Ljubljana - Melania',
    '171:London - Crumpets',
    '341:London - Custard',
    '321:Los Angeles - Cube',
    '107:Los Angeles - Dogg',
    '310:Los Angeles - Lamar',
    '152:Luxembourg - Chemin',
    '427:Madrid - Plaza Mayor',
    '115:Madrid - Prado',
    '126:Manchester - United',
    '365:Manila - Hotdog',
    '411:Marseille - La Marseillaise',
    '356:Melbourne - Port Phillip',
    '224:Melbourne - Yarra',
    '326:Miami - Florida Man',
    '140:Miami - Vice',
    '318:Milan - Duomo',
    '110:Milan - Galleria',
    '316:Montreal - Bagel Poutine',
    '359:Montreal - Expo 67',
    '372:Mumbai - Mahim',
    '389:Nairobi - Sigiria',
    '417:New Delhi - Chole Bhature',
    '106:New York - Empire',
    '384:New York - Grand Central',
    '330:New York - Insomnia',
    '320:Nicosia - Blue Lagoon',
    '410:Novi Travnik - Pisanica',
    '336:Orlando - Tofu Driver',
    '169:Oslo - Fjord',
    '433:Oslo - Rakfisk',
    '428:Palermo - Sicilicious',
    '443:Panama City - Canal',
    '358:Panama City - Papers',
    '342:Paris - Jardin',
    '103:Paris - Seine',
    '355:Perth - Herdsman',
    '223:Perth - Kings Park',
    '348:Philadelphia - Fresh Prince',
    '413:Philadelphia - Sunny',
    '325:Phoenix - Floatie',
    '88:Prague - Staromak',
    '338:Prague - Vltava',
    '420:Querétaro - Aqueduct',
    '385:Quito - Cuy',
    '121:Reykjavik - Fuzzy Pony',
    '344:Reykjavik - Reyka',
    '254:Riga - Daugava',
    '398:Riga - Saeima',
    '211:Saint Petersburg - Shnur',
    '442:Salt Lake City - Temple Sqr',
    '329:San Francisco - Sanitation',
    '337:San Jose - Santana',
    '333:Santa Clara - Inside',
    '373:Santiago - Cueca',
    '231:Sao Paulo - Mercadao',
    '165:Sao Paulo - Pinacoteca',
    '286:Sarajevo - Burek',
    '290:Seattle - Cobain',
    '221:Seattle - Cornell',
    '182:Seattle - Hendrix',
    '399:Seoul - Han River',
    '362:Seoul - Hangang',
    '170:Singapore - Garden',
    '235:Singapore - Marina Bay',
    '241:Singapore - SMRT',
    '339:Skopje - Vardar',
    '100:Sofia - Nevski',
    '437:Sofia - Vitoshka',
    '388:South Bend - Hawkins',
    '234:Stockholm - Djurgarden',
    '159:Stockholm - Ikea',
    '30:Stockholm - Syndrome',
    '226:Sydney - Opera House',
    '243:Sydney - Squidney',
    '314:Taipei - Datong',
    '299:Tallinn - Lennujaam',
    '349:Tampa - Cuban Sandwich',
    '387:Tbilisi - Ghvino',
    '283:Tirana - Besa',
    '423:Tirana - Fergese',
    '148:Tokyo - Shinkansen',
    '287:Tokyo - Wabi-sabi',
    '197:Toronto - Comfort Zone',
    '72:Toronto - The 6',
    '332:Troll - Station',
    '187:Vancouver - Granville',
    '124:Vancouver - Stanley',
    '311:Vancouver - Vansterdam',
    '308:Vienna - Boltzmann',
    '87:Vienna - Hofburg',
    '378:Vilnius - Neris',
    '237:Warsaw - Curie',
    '309:Warsaw - Vistula',
    '324:Washington DC - Trade War',
    '252:Zagreb - Tkalciceva',
    '112:Zurich - Alphorn',
    '264:Zurich - Altstadt',
    '317:Zurich - Lindenhof'
];
